-- 코드를 작성해주세요
SELECT THIRD.ID
FROM ECOLI_DATA THIRD
WHERE PARENT_ID IN (
    SELECT SECOND.ID
    FROM ECOLI_DATA SECOND
    WHERE PARENT_ID IN (
        SELECT FIRST.ID
        FROM ECOLI_DATA FIRST
        WHERE PARENT_ID IS NULL
    )
);