-- 코드를 작성해주세요
WITH RECURSIVE PARENT AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, C.PARENT_ID, P.GEN + 1 AS GEN
    FROM ECOLI_DATA C
    JOIN PARENT P ON P.ID = C.PARENT_ID
)
SELECT COUNT(*) COUNT, GEN GENERATION
FROM PARENT P
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE P.ID = E.PARENT_ID
)
GROUP BY GEN
ORDER BY GEN;