-- 코드를 입력하세요
-- FOOD_ORDER - AMOUNT, PRODUCE_DATE
-- FOOD_PRODUCT - PRICE, PRODUCT_ID, PRODUCT_NAME
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_SALES) TOTAL_SALES
FROM (
    SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT TOTAL_SALES, O.PRODUCE_DATE
    FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O USING (PRODUCT_ID)
    WHERE YEAR(O.PRODUCE_DATE) = 2022 
    AND MONTH(O.PRODUCE_DATE) = 5
) TMP
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, 1;