-- 코드를 입력하세요
WITH TOTAL AS (
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    
    UNION ALL
    
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM JULY
)
SELECT FLAVOR
FROM (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER)
    FROM TOTAL
    GROUP BY FLAVOR
    ORDER BY 3 DESC
    LIMIT 3) TOTAL3;